apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rate-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $MONGODB_RATE_STORAGE
  resources:
    requests:
      storage: 400Mi