apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $MONGODB_USER_STORAGE
  resources:
    requests:
      storage: 400Mi