apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $MONGODB_PROFILE_STORAGE
  resources:
    requests:
      storage: 400Mi