apiVersion: v1
kind: PersistentVolume
metadata:
  name: $MONGODB_RATE_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Mi
  storageClassName: $MONGODB_RATE_STORAGE
  hostPath:
    path: /data/volumes/rate-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - "2"
