apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $MONGODB_RESERVATION_STORAGE
  resources:
    requests:
      storage: 400Mi